
name = "Imgur Uploader"
command = "imgur-uploader"

[docker]
    image = "Dockerfile"
    working_dir = "/"

[arguments]

    [arguments.inputfile]
        shorthand = "*"
        argType = "string"
        docker = "inOutFile"

    [arguments.title]
        argType = "string"
        docker = "passthrough"